import{i as l,S as y}from"./assets/vendor-5b791d57.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))u(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&u(a)}).observe(document,{childList:!0,subtree:!0});function h(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function u(t){if(t.ep)return;t.ep=!0;const o=h(t);fetch(t.href,o)}})();const g="42473216-758414b66288a27fb7f33990e",p="https://pixabay.com/api/";class m{constructor(){this.userQuery="",this.page=1}async fetchArticles(){const e=await axios.get(`${p}?key=${g}&q=${this.userQuery}&image_type=photo&orientation=horizontal&safesearch=true&page=${this.page}&per_page=15`);return this.incrementPage(),e.data}incrementPage(){this.page+=1}resetPage(){this.page=1}get query(){return this.userQuery}set query(e){this.userQuery=e}}function L(r){return r.hits.map(e=>`
            <li class="gallery-item"><a href="${e.largeImageURL}">
          <img class="gallery-image" src="${e.webformatURL}" alt="${e.tags}"></a>
          <p>Likes: ${e.likes}</p>
          <p>Views: ${e.views}</p>
          <p>Comments: ${e.comments}</p>
          <p>Downloads: ${e.downloads}</p>
          </li>`).join("")}const d=document.querySelector(".search-form"),n=document.querySelector(".gallery"),s=document.querySelector('[data-action="load-more"]'),c=document.querySelector(".loader"),i=new m;d.addEventListener("submit",b);s.addEventListener("click",S);function b(r){if(c.style.display="inline-block",n.innerHTML="",r.preventDefault(),P(),i.userQuery=r.currentTarget.elements.searchQuery.value,i.userQuery.trim()===""){c.style.display="none",l.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topLeft",transitionIn:"fadeInLeft"});return}i.resetPage(),i.fetchArticles().then(function(e){c.style.display="none",w(),f(e),e.hits.length===0&&(l.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topLeft",transitionIn:"fadeInLeft"}),s.classList.add("is-hidden"))}).catch(function(e){console.log(e)})}function S(){i.fetchArticles().then(function(r){f(r),v(),n.children.length>=r.totalHits&&(l.error({message:"We are sorry, but you have reached the end of search results.",position:"topCenter",transitionIn:"fadeInLeft"}),s.classList.add("is-hidden"))})}function w(){s.classList.remove("is-hidden")}function v(){const{height:r}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}function f(r){n.insertAdjacentHTML("beforeend",L(r));const e=new y(".gallery a",q);e.on("show.simplelightbox"),e.refresh(),d.reset()}function P(){n.innerHTML=""}const q={captions:!0,captionType:"attr",captionsData:"alt",captionPosition:"bottom",captionSelector:"img",captionDelay:250};
//# sourceMappingURL=commonHelpers.js.map
