import{i as c,S as y}from"./assets/vendor-5b791d57.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))l(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&l(a)}).observe(document,{childList:!0,subtree:!0});function m(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function l(t){if(t.ep)return;t.ep=!0;const o=m(t);fetch(t.href,o)}})();const g="42473216-758414b66288a27fb7f33990e",p="https://pixabay.com/api/";class L{constructor(){this.userQuery="",this.page=1}async fetchArticles(){const e=await axios.get(`${p}?key=${g}&q=${this.userQuery}&image_type=photo&orientation=horizontal&safesearch=true&page=${this.page}&per_page=15`);return this.incrementPage(),e.data}incrementPage(){this.page+=1}resetPage(){this.page=1}get query(){return this.userQuery}set query(e){this.userQuery=e}}function d(r){return console.log(r),r.hits.map(e=>`
            <li class="gallery-item"><a href="${e.largeImageURL}">
          <img class="gallery-image" src="${e.webformatURL}" alt="${e.tags}"></a>
          <p>Likes: ${e.likes}</p>
          <p>Views: ${e.views}</p>
          <p>Comments: ${e.comments}</p>
          <p>Downloads: ${e.downloads}</p>
          </li>`).join("")}document.querySelector(".search-input");const f=document.querySelector(".search-form"),n=document.querySelector(".gallery");document.querySelector("div");const s=document.querySelector('[data-action="load-more"]'),u=document.querySelector(".loader"),i=new L;f.addEventListener("submit",b);s.addEventListener("click",S);function b(r){if(u.style.display="inline-block",n.innerHTML="",r.preventDefault(),w(),i.userQuery=r.currentTarget.elements.searchQuery.value,setTimeout(()=>{u.style.display="none"},100),i.userQuery.trim()===""){c.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topLeft",transitionIn:"fadeInLeft"});return}q(),i.resetPage(),i.fetchArticles().then(function(e){h(e),e.hits.length===0&&(c.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topLeft",transitionIn:"fadeInLeft"}),s.classList.add("is-hidden"))}).catch(function(e){console.log(e)})}function S(){i.fetchArticles().then(function(r){h(r),v(),n.children.length>=r.totalHits&&(c.error({message:"We are sorry, but you have reached the end of search results.",position:"topCenter",transitionIn:"fadeInLeft"}),s.classList.add("is-hidden"))})}function q(){s.classList.remove("is-hidden")}function v(){const{height:r}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}d(response);function h(r){n.insertAdjacentHTML("beforeend",d(r));const e=new y(".gallery a",P);e.on("show.simplelightbox"),e.refresh(),f.reset(),hideLoader()}function w(){n.innerHTML=""}const P={captions:!0,captionType:"attr",captionsData:"alt",captionPosition:"bottom",captionSelector:"img",captionDelay:250};
//# sourceMappingURL=commonHelpers.js.map
